version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-documentsdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: documentsdb
      POSTGRES_USER: documents_app
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documents_user -d documentsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
